export const ACCOUNTS_RECEIVABLE_STATUS = {
  PENDING: 'PENDIENTE',
  PAID: 'PAGADO'
}

export const PROCESSES_STATUS = {
  PENDING: 'PENDIENTE',
  FINISHED: 'FINALIZADO'
}

export const UNITS = {
  LITERS: 'LITROS',
  MILILITERS: 'MILILITROS',
  KILOS: 'KILOS',
  GRAMS: 'GRAMOS',
  ITEMS: 'PIEZAS'
}

export const PRODUCT_TYPES = {
  RAW_MATERIAL_PRODUCT: 'MATERIA PRIMA',
  SIMPLE_PRODUCT: 'PRODUCTO',
  PACKAGING_PRODUCT: 'EMBALAJES',
  FINISHED_PRODUCT: 'PRODUCTO TERMINADO'
}

export const WAREHOUSE_TYPES = {
  RAW_MATERIAL_WAREHOUSE: 'MATERIA PRIMA',
  SIMPLE_PRODUCT_WAREHOUSE: 'PRODUCTO',
  PACKAGING_PRODUCT_WAREHOUSE: 'EMBALAJES',
  FINISHED_PRODUCT_WAREHOUSE: 'PRODUCTO TERMINADO'
}

export const PURCHASE_ORDERS_PERIODS = [
  {
    id: 1,
    label: 'CONTADO',
    value: 0
  },
  {
    id: 2,
    label: '15 DÍAS',
    value: 15
  },
  {
    id: 3,
    label: '30 DÍAS',
    value: 30
  }
]

export const LOGBOOK_TYPES = {
  PURCHASE: 'COMPRA',
  SALE: 'VENTA'
}

export const CHARTS_DEFAULT_COLORS = [
  '#0C923F',
  '#3DA765',
  '#6EBC8C',
  '#9FD0B2'
]
export const CHARTS_LAVANDER_COLORS = [
  '#C230D4',
  '#CE61DC',
  '#D988E3',
  '#E3B0E9'
]
export const CHARTS_BLUE_COLORS = ['#204983', '#204983', '#7A91B3', '#A6B5CB']
export const CHARTS_YELLOW_COLORS = ['#FAC12E', '#F8CE5F', '#F7D887', '#F7D887']
export const CHARTS_ORANGE_COLORS = ['#F97921', '#F89856', '#F7B180', '#F6C9AB']
export const CHARTS_RED_COLORS = ['#E22850', '#E65373', '#EA7E96', '#EEA9B8']

export const CHARTS_COLORS = {
  GREEN: {
    500: CHARTS_DEFAULT_COLORS[0],
    400: CHARTS_DEFAULT_COLORS[1],
    300: CHARTS_DEFAULT_COLORS[2],
    200: CHARTS_DEFAULT_COLORS[3]
  },
  BLUE: {
    500: CHARTS_BLUE_COLORS[0],
    400: CHARTS_BLUE_COLORS[1],
    300: CHARTS_BLUE_COLORS[2],
    200: CHARTS_BLUE_COLORS[3]
  },
  YELLOW: {
    500: CHARTS_YELLOW_COLORS[0],
    400: CHARTS_YELLOW_COLORS[1],
    300: CHARTS_YELLOW_COLORS[2],
    200: CHARTS_YELLOW_COLORS[3]
  },
  ORANGE: {
    500: CHARTS_ORANGE_COLORS[0],
    400: CHARTS_ORANGE_COLORS[1],
    300: CHARTS_ORANGE_COLORS[2],
    200: CHARTS_ORANGE_COLORS[3]
  },
  RED: {
    500: CHARTS_RED_COLORS[0],
    400: CHARTS_RED_COLORS[1],
    300: CHARTS_RED_COLORS[2],
    200: CHARTS_RED_COLORS[3]
  },
  LAVANDER: {
    500: CHARTS_LAVANDER_COLORS[0],
    400: CHARTS_LAVANDER_COLORS[1],
    300: CHARTS_LAVANDER_COLORS[2],
    200: CHARTS_LAVANDER_COLORS[3]
  }
}

export const PIE_CHART_LOTS_COLORS = [
  CHARTS_COLORS.GREEN[500],
  CHARTS_COLORS.BLUE[500],
  CHARTS_COLORS.YELLOW[500],
  CHARTS_COLORS.ORANGE[500],
  CHARTS_COLORS.RED[500],
  CHARTS_COLORS.LAVANDER[500],
  CHARTS_COLORS.GREEN[400],
  CHARTS_COLORS.BLUE[400],
  CHARTS_COLORS.YELLOW[400],
  CHARTS_COLORS.ORANGE[400],
  CHARTS_COLORS.RED[400],
  CHARTS_COLORS.LAVANDER[400],
  CHARTS_COLORS.GREEN[300],
  CHARTS_COLORS.BLUE[300],
  CHARTS_COLORS.YELLOW[300],
  CHARTS_COLORS.ORANGE[300],
  CHARTS_COLORS.RED[300],
  CHARTS_COLORS.LAVANDER[300],
  CHARTS_COLORS.GREEN[200],
  CHARTS_COLORS.BLUE[200],
  CHARTS_COLORS.YELLOW[200],
  CHARTS_COLORS.ORANGE[200],
  CHARTS_COLORS.RED[200],
  CHARTS_COLORS.LAVANDER[200]
]
