export const PROCESSES_STATUS = {
  PENDING: 'PENDIENTE',
  FINISHED: 'FINALIZADO'
}

export const UNITS = {
  LITERS: 'LITROS',
  MILILITERS: 'MILILITROS',
  KILOS: 'KILOS',
  GRAMS: 'GRAMOS',
  ITEMS: 'PIEZAS'
}

export const PRODUCT_TYPES = {
  RAW_MATERIAL_PRODUCT: 'MATERIA PRIMA',
  SIMPLE_PRODUCT: 'PRODUCTO',
  PACKAGING_PRODUCT: 'EMBALAJES',
  FINISHED_PRODUCT: 'PRODUCTO TERMINADO'
}

export const WAREHOUSE_TYPES = {
  RAW_MATERIAL_WAREHOUSE: 'MATERIA PRIMA',
  SIMPLE_PRODUCT_WAREHOUSE: 'PRODUCTO',
  PACKAGING_PRODUCT_WAREHOUSE: 'EMBALAJES',
  FINISHED_PRODUCT_WAREHOUSE: 'PRODUCTO TERMINADO'
}
